### ISSUE TITLE
Week 45 tracking issue

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1780]
This week I'm on leave working 100% with sitespeed.io. This is the tracking issue with the work I plan 2do.

## Bugs
- [x] Better handling of video from Android https://github.com/sitespeedio/sitespeed.io/issues/1738
- [x] Wrong exist status on errors https://github.com/sitespeedio/sitespeed.io/issues/1267
- [x] Jenkins problem https://github.com/sitespeedio/sitespeed.io/issues/1774

## Documentation
- [x] Redo the start page in the docs
- [x] Go through all the docs and update them (add new items that should be fixed)
- [x] Browsertime docs
- [x] Performance Dashboard docs (we need update this one)
- [x] Example page
- [x] Add a best practice section
- [x]  Update documentation/sitespeed.io/docker/
- [x] Update documentation/sitespeed.io/performance-budget/
- [ ] Update documentation/sitespeed.io/use-cases/
- [ ] Update documentation/sitespeed.io/upgrade/
- [x] Add documentation/sitespeed.io/alerts/

## Changes
- [x] Start sending pug files, the overall goal is to make plugins create HTML
- [ ] Rename tabs from the tools to what kind of data that you actually have in that tab. Change PageXray/Browsertime etc to Waterfall/Video or something like that.
- [x] Go through Coach advice
- [ ] Release Coach 1.0
- [ ] Create containers with WebPageReplay for Browsertime and sitespeed.io
- [ ] Remove old Docker containers
- [ ] Look into run more JavaScript in Browsertime (navigate with JavaScript)
- [ ] Add link to compare page from result page

## Maintain
- [ ] Close old issues 
- [ ] Remove old versions (4.x) versions at the Docker hub.

**Comment by soulgalore** [comment]
The week is over lets create a tracking issue what's needs to be done to release 6.0
