### ISSUE TITLE
[Tracking] Browser bugs

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1824]
Here are the known bugs that effect running tests in sitespeed.io

## Chrome
 - [ ] Running on emulated mobile sets the window size wrong on Linux and that makes the screen flicker at the end of the run, giving us wrong last visual change. Introduced in Chrome 61. See https://bugs.chromium.org/p/chromium/issues/detail?id=776053 You can probably work around it by setting width/height user agent yourself.

## Firefox
 - [ ] Firefox 55-57 is missing a way to export the HAR file (that's why our Docker container still is running Firefox 54. Mozilla says a new plugin will be there Q4.
 - [ ] Firefox 57 has a sometimes gives wrong navigation timing values https://bugzilla.mozilla.org/show_bug.cgi?id=1417308

**Comment by soulgalore** [comment]
I think these have been fixed upstream! :)
